### ISSUE TITLE
Add support to Visual Studio 2019

### ISSUE THREAD

**Issue by igorgomeslima** [Kir-Antipov/LineSorter#1]
Please :)!

**Comment by Kira-NT** [comment]
## Good news!
I've finally installed Visual Studio 2019 and now I can safely say: the extension is **fully compatible** with the new API!)

--------

I'm sorry for such a long wait! The extension will be available at the [Marketplace](https://marketplace.visualstudio.com/items?itemName=KirAntipov.LineSorterByKir) immediately after the first update!

**Comment by igorgomeslima** [comment]
So Nice @Kir-Antipov! ;)
