### ISSUE TITLE
Split blocks after sorting

### ISSUE THREAD

**Issue by Sayanel01** [Kir-Antipov/LineSorter#17]
I use this extension to sort the `includes` of my c++ files.

I would like to split each group of lines after sorting, like this :

*Before*

    #include "folder1/somename/file1.h"
    #include "folder2/file2.h"
    #include "folder1/anothername/file3.h"
    #include "folder2/file4.h"

*After sort*

    #include "folder1/anothername/file3.h"
    #include "folder1/somename/file1.h"
    #include "folder2/file2.h"
    #include "folder2/file4.h"

*Final result*

    #include "folder1/anothername/file3.h"
    #include "folder1/somename/file1.h"

    #include "folder2/file2.h"
    #include "folder2/file4.h"

Where a blank line has been added to mark the limit between "folder1/" and "folder2/".

Is there currently a way to do this using line sorter? Or how could I post-process with another extension ?

**Comment by Kira-NT** [comment]
I apologize for the late response; I'm a bit overbooked at the moment.

LineSorter allows you to create custom sorting rules. If you look at the interface of a custom user sort here:

[https://github.com/Kir-Antipov/LineSorter/blob/d53c3057f770a2513a00417fb82c557b99e45e14/LineSorter.Export/IUserSort.cs#L10](https://github.com/Kir-Antipov/LineSorter/blob/d53c3057f770a2513a00417fb82c557b99e45e14/LineSorter.Export/IUserSort.cs#L10)

You will see that it takes a collection of strings and returns a processed one back. There are no hard limits on what you can do with the strings provided to you; you can delete and add new ones, not just reorganize existing ones.

So, to implement the behavior you want, follow these steps:

1. Right-click to open the context menu
2. Select "Line Sorter"
3. Choose "Add custom sort"
4. Choose a name for your custom sorting rule
5. Change the "Function type" to "Full implementation (Func<IEnumerable<T>, IEnumerable<T>>)"
6. Paste the following code (note that the function signature is readonly and provided by the editor):

    ```csharp
    public IEnumerable<string> Sort(IEnumerable<string> Source)
    {
        // Separator(s) used to split a string to get its group name.
        var separators = new char[] { '/' };
    
        // Change this if you need multiple empty lines between the groups.
        var emptyLines = new string[] { string.Empty };
    
        // Sort the lines using the regular comparison rules.
        var sortedSource = Source.OrderBy(x => x);
    
        // Group the sorted lines.
        var groups = sortedSource.GroupBy(x => separators.All(s => x.IndexOf(s) == -1) ? string.Empty : x.Split(separato
    rs, StringSplitOptions.RemoveEmptyEntries)[0]);
    
        // Prepend empty lines to each group except the first one.
        var concatenatedGroups = groups.SelectMany((x, i) => i == 0 ? x : emptyLines.Concat(x));
    
        return concatenatedGroups;
    }
    ```

7. Press "Compile"
8. Done

And you're all set! Your custom sorting rule should now be available in the context menu of LineSorter.



If we sort these `includes`:

```
#include "folder1/somename/file1.h"
#include "folder2/file2.h"
#include "folder1/anothername/file3.h"
#include "folder2/file4.h"
#include "file6.h"
#include "file5.h"
```

The result should be as follows:

```
#include "file5.h"
#include "file6.h"

#include "folder1/anothername/file3.h"
#include "folder1/somename/file1.h"

#include "folder2/file2.h"
#include "folder2/file4.h"
```

Hope this helps!

**Comment by Sayanel01** [comment]
Thank you very much to have taken the time create the full solution, that's perfect.
