### ISSUE TITLE
LineSorter is not available in .json context menu

### ISSUE THREAD

**Issue by zTechSoul** [Kir-Antipov/LineSorter#4]
Hello.

Thanks for the extension. It is helpful for sure.
At the same time I've faced the issue of not being able to find LineSorter option in .json editor context menu:
![image](https://user-images.githubusercontent.com/9977125/53983147-6d6e6180-40cb-11e9-9292-6320aea76e35.png)

Also I couldn't find corresponding options among the list of available commands in ContextMenu editor of Visual Studio 2017

Please, consider supporting **.json**s and/or adding LineSorter options to the list of available commands.

Regards,
Andrey

**Comment by Kira-NT** [comment]
I apologize for the inconvenience! Tomorrow everything will be fixed)

**Comment by zTechSoul** [comment]
Kir, thanks a lot.

**Comment by Kira-NT** [comment]
Finally it's time to solve your problem!

Update can already be downloaded in the [Marketplace](https://marketplace.visualstudio.com/items?itemName=KirAntipov.LineSorterByKir)

If you encounter a similar problem in the future, simply create a pull request in which you must change the following lines in the [Structures.ttinclude](https://github.com/Kir-Antipov/LineSorter/blob/master/LineSorter/Templates/Structures.ttinclude):

```
public static ContextMenu[] Menus { get; } = new ContextMenu[] {
    new ContextMenu("XAML", "{4C87B692-1202-46AA-B64C-EF01FAEC53DA}", "259"),
    new ContextMenu("JSON", "{F718CA06-CF4F-4A0C-9106-E79E9EE5E7CD}", "3")
};
```
Simply push `new ContextMenu(HumanReadableName, ContextMenuGUID, CmdID)` into this array! (To find out the Guid and CmdID of the required context menu, turn on VSIP Logging, then open VisualStudio, open the file you need, hold down Shift + Ctrl, and then click RMB. In the window that opens there will be all the necessary information!)
