### ISSUE TITLE
Add custom sort not working for unknown reasons

### ISSUE THREAD

**Issue by mobergs** [Kir-Antipov/LineSorter#7]
Add custom sort does nothing, window closes and no indicator of compile or visible custom sort menu item.   Following the "Add custom command myself" shows the custom sort in the Options window but clear way to invoke the custom sort

**Comment by Kira-NT** [comment]
Latest VS2019:

![0](https://user-images.githubusercontent.com/40232067/68245315-c9590380-0027-11ea-8413-a0d81a6bc048.png)
![1](https://user-images.githubusercontent.com/40232067/68245317-c9590380-0027-11ea-9ff7-2662d562fd7d.png)
![2](https://user-images.githubusercontent.com/40232067/68245318-c9590380-0027-11ea-8d4c-67aeb6819f09.png)
![3](https://user-images.githubusercontent.com/40232067/68245319-c9f19a00-0027-11ea-905b-302121219e7f.png)

Could you check `%LocalAppData%/KE/Common` path, please? 
There should be a folder `roslyn` containing the latest versions of C# and VB compilers. It’s possible that for some reason the folder doesn't exist, or it doesn't have everything necessary, so try deleting it and starting Visual Studio again, then click on LineSorter in the Options (one way to force Visual Studio to immediately initialize the extension) and wait some time until the extension pulls up the necessary compilers.

**Comment by Kira-NT** [comment]
Haven't seen you for a while, and since you are the only one who has encountered such a problem and I have no any details about it, I don't think this issue needs to be open. If the problem will persist and you'll be ready to provide some details about it - feel free to reopen this issue
