### ISSUE TITLE
Random behavior with leading whitespace and quotes

### ISSUE THREAD

**Issue by twallgren** [Kir-Antipov/LineSorter#8]
If I am working in a part of the code that is indented (I use 4 space indenting) and try to sort them, sometimes each line will be increasingly indented (1st line has 4 spaces, 2nd has 8, 3rd has 12, etc). Whenever this happens, it also has issues with double quotes. For example, in my web.config file, this line:
`<add key="Timeout" value="45" />`
will become this (notice the two double quotes before 45):
`            <add key="Timeout" value=""45" />`

If I highlight the same lines and repeat the sorting these issues happen about 25% of the time.

**Comment by twallgren** [comment]
Here's my setup info copied from VS: 

Microsoft Visual Studio Professional 2019
Version 16.3.8
VisualStudio.16.Release/16.3.8+29503.13
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

ApexSQL Refactor   1.0
ApexSQL Refactor Visual Studio Addin Component

ApexSQL Stub   1.0


ASP.NET and Web Tools 2019   16.3.286.43615
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.286.43615
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.286.43615
Azure App Service Tools v3.0.0

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.2.3   Build 192.0.20191016.60459
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

LineSorter Extension   1.0
LineSorter Visual Studio Extension Detailed Info

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.3.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

StopOnFirstBuildError   1.0
StopOnFirstBuildError

Stops a solution build immediately after a project has failed to build.

http://tech.einaregilsson.com/2011/01/06/stop-build-on-first-error-in-visual-studio-2010/

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VSColorOutput   2.6.7
Color output for build and debug windows - https://mike-ward.net/vscoloroutput

**Comment by Kira-NT** [comment]
Hi!
Could you upload a minimal example on which I can see this problem (without your personal data), please?

I also need to know what sorting you're using. If you use custom sorting, I'll need its code!

**Comment by Kira-NT** [comment]
Haven't seen you for a while, and since you are the only one who has encountered such a problem (LineSorter doesn't change any line's content such `"`, so problem might be outside my extension) and I have no enough details about it, I don't think this issue needs to be open. 

If the problem will persist and you'll be ready to provide some details about it - feel free to reopen this issue
