### ISSUE TITLE
When can I install in SSMS as well?

### ISSUE THREAD

**Issue by ghost** [Kir-Antipov/LineSorter#9]
Not really fair to raise this as an issue, but as far as you're concerned, I'm a USER -- so you should have expected it. ;)

I once wrote my own for SSMS, then lost it in the sands of time. Before I invest the time to recreate, how about making yours available in both environments? If you think it's a fine idea that *I* should tackle, I'm not opposed (just pressed for time at present).

**Comment by Kira-NT** [comment]
I'm one of those old-fashioned people who design databases on paper and do all the work through the console, so I had never used SSMS. And also I haven't heard before that this environment supports extensions. At least there's definitely no marketplace for them :)

I don’t think that I can be useful in porting even my extension to an environment I know nothing about. However, you can always fork the repository and try porting it by yourself ¯\\_(ツ)_/¯

**Comment by ghost** [comment]
Sorry for taking so long to respond. I’m happy to give it a shot, hopefully I can get to it in April.

SSMS is, I believe, a specialized version of Visual Studio. Originally it was an older version of VS that was used, but maybe by now they’re in sync? I dunno. I’m absolutely fascinated to understand more about how you work. When you say “console”, do you mean that you run SQLCMD from the “DOS prompt” or “cmd.exe”? Do you work with the db often? While working with SSMS is (I imagine) a little faster, your approach might improve the odds of catching deployment-related bugs much earlier. Please, can you tell me your approach in more detail?

Thanks!

**Comment by Kira-NT** [comment]
Better late than never :)

> SSMS 18.x is built on the Visual Studio 2017 shell and is subject to the limitations of that environment.

© [MSDN](https://docs.microsoft.com/en-us/sql/ssms/install-extensions-in-sql-server-management-studio-ssms?view=sql-server-ver15)

As far as I can tell, SSMS should support extensions made for version of Visual Studio it's built on. LineSorter supports VS 2017+, so you should be able to install it in SSMS 18.x+

Maybe I need to add some specific `InstallationTarget` to the vsixmanifest, but I didn't find information about it. So, just try to install the extension, and hopefully it will work :)

**Comment by ghost** [comment]
I’m sorry Kir, I didn’t see your replies until now – there was no notification until, I’m guessing, you changed the status. Thank you for continuing to look into this.
